jobs:
  include:
      # Linux Jobs
    - os: linux
      language: python
      python: 3.6
      before_install: 
        - sudo apt-get -y install ffmpeg
        - sudo apt-get -y install texlive texlive-latex-extra texlive-fonts-extra texlive-latex-recommended texlive-science texlive-fonts-extra tipa
      install:
        - pip3 install --upgrade pip
        - pip3 install -r ./.travis/travis-requirements.txt
        - pip3 install pycairo pytest
        - pip3 install .
      script:
        - pytest

    - os: linux
      language: python
      python: 3.7
      before_install: 
              - sudo apt-get -y install ffmpeg
              - sudo apt-get -y install texlive texlive-latex-extra texlive-fonts-extra texlive-latex-recommended texlive-science texlive-fonts-extra tipa        
      install:
        - pip3 install --upgrade pip
        - pip3 install -r ./.travis/travis-requirements.txt
        - pip3 install pycairo pytest
        - pip3 install .
      script:
        - pytest

    - os: linux
      language: python
      python: 3.8
      before_install: 
        - sudo apt-get -y install ffmpeg
        - sudo apt-get -y install texlive texlive-latex-extra texlive-fonts-extra texlive-latex-recommended texlive-science texlive-fonts-extra tipa
      install:
        - pip3 install --upgrade pip
        - pip3 install -r ./.travis/travis-requirements.txt
        - pip3 install pycairo pytest
        - pip3 install .
      script:
        - pytest

      # MacOS (OSX) Jobs
    - os: osx
      language: sh
      python: 3.6
      env: PYVER="3.6.10"
      before_install: 
        - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
        - brew install ffmpeg
        - brew cask install mactex
        - eval "$(/usr/libexec/path_helper)"
      install:
        - pip3 install --upgrade pip
        - pip3 install -r ./.travis/travis-requirements.txt
        - pip3 install pycairo pytest
        - pip3 install .
      script:
        - pytest

    - os: osx
      language: sh
      python: 3.7
      env: PYVER="3.7.7"
      before_install: 
        - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
        - brew install ffmpeg
        - brew cask install mactex
        - eval "$(/usr/libexec/path_helper)"
      install:
        - pip3 install --upgrade pip
        - pip3 install -r ./.travis/travis-requirements.txt
        - pip3 install pycairo pytest
        - pip3 install .
      script:
        - pytest

    - os: osx
      language: sh
      python: 3.8
      env: PYVER="3.8.0" # Using Python 3.8.0 due to error with rich
      before_install: 
        - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
        - brew install ffmpeg
        - brew cask install mactex
        - eval "$(/usr/libexec/path_helper)"
      install:
        - pip3 install --upgrade pip
        - pip3 install -r ./.travis/travis-requirements.txt
        - pip3 install pycairo pytest
        - pip3 install .
      script:
        - pytest

      # Windows Jobs
    - os: windows
      language: sh
      python: 3.6
      # the latest version available on chocolatey is 3.6.8
      env: PYVER="3.6.8" PYDIR="Python36"
      install:
        - choco install python --version=$PYVER
        - export PATH="/c/$PYDIR:/c/$PYDIR/Scripts:$PATH"
        - cmd.exe //c "RefreshEnv.cmd"
        - python -m pip install --upgrade pip
        - python -m pip install --user -r ./.travis/travis-requirements.txt
        - python ./scripts/pycairoinstall.py
        - cmd.exe //c "RefreshEnv.cmd"
        - python -m pip install --user .
      script: 
        - python -m pytest --skip_end_to_end -rs

    - os: windows
      language: sh
      python: 3.7
      env: PYVER="3.7.7" PYDIR="Python37"
      install:
        - choco install python --version=$PYVER
        - export PATH="/c/$PYDIR:/c/$PYDIR/Scripts:$PATH"
        - cmd.exe //c "RefreshEnv.cmd"
        - python -m pip install --upgrade pip
        - python -m pip install --user -r ./.travis/travis-requirements.txt
        - python ./scripts/pycairoinstall.py
        - cmd.exe //c "RefreshEnv.cmd"
        - python -m pip install --user .
      script: 
        - python -m pytest --skip_end_to_end -rs

    - os: windows
      language: sh
      python: 3.8
      env: PYVER="3.8.0" PYDIR="Python38" # Using Python 3.8.0 due to error with rich
      install:
        - choco install python --version=$PYVER
        - export PATH="/c/$PYDIR:/c/$PYDIR/Scripts:$PATH"
        - cmd.exe //c "RefreshEnv.cmd"
        - python -m pip install --upgrade pip
        - python -m pip install --user -r ./.travis/travis-requirements.txt
        - python ./scripts/pycairoinstall.py
        - cmd.exe //c "RefreshEnv.cmd"
        - python -m pip install --user .
      script: 
        - python -m pytest --skip_end_to_end -rs

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then chmod +x ./.travis/osx.sh; sh ./.travis/osx.sh; fi

branches:
  only:
  - master

notifications:
  email: false
